// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDS9-PovCSGSTeg0HQ1r6jEGA_asfV-FfM',
    appId: '1:464997811328:web:779a3380003044f5ddd265',
    messagingSenderId: '464997811328',
    projectId: 'flutter-my-chat-app-myself',
    authDomain: 'flutter-my-chat-app-myself.firebaseapp.com',
    storageBucket: 'flutter-my-chat-app-myself.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3o6PLIfaE4d93f9BllEtZATW3uMVo0fk',
    appId: '1:464997811328:android:81b00073cc9659a8ddd265',
    messagingSenderId: '464997811328',
    projectId: 'flutter-my-chat-app-myself',
    storageBucket: 'flutter-my-chat-app-myself.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB--GvRXA0Wv2WXI0skTWoC25cF9fiij6M',
    appId: '1:464997811328:ios:43c1ead070705511ddd265',
    messagingSenderId: '464997811328',
    projectId: 'flutter-my-chat-app-myself',
    storageBucket: 'flutter-my-chat-app-myself.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB--GvRXA0Wv2WXI0skTWoC25cF9fiij6M',
    appId: '1:464997811328:ios:43c1ead070705511ddd265',
    messagingSenderId: '464997811328',
    projectId: 'flutter-my-chat-app-myself',
    storageBucket: 'flutter-my-chat-app-myself.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDS9-PovCSGSTeg0HQ1r6jEGA_asfV-FfM',
    appId: '1:464997811328:web:4de7c17ff063ff42ddd265',
    messagingSenderId: '464997811328',
    projectId: 'flutter-my-chat-app-myself',
    authDomain: 'flutter-my-chat-app-myself.firebaseapp.com',
    storageBucket: 'flutter-my-chat-app-myself.appspot.com',
  );
}
